name: 🔁 HTML aus CSV-Dateien generieren

on:
  push:
    paths:
      - 'Spielplan_*.csv'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: 📥 Repository klonen
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: 🐍 Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Abhängigkeiten installieren
        run: pip install pandas

      - name: 🛠 HTML generieren aus CSV-Dateien
        run: python generate_from_csv.py

      - name: 🔁 Commit und Push via Token
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/index.html
          git commit -m "📅 HTML-Aktualisierung" || echo "nichts zu committen"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/uscmuenster/USC-Spielplaene2526.git
